"""
ADER--DG solver in PyTorch for the 1D low-Froude shallow-water--Exner system.

This file implements the algorithm written in ADER_DG_Exner_Low_Froude.tex:

    U = (eta, q, b)^T,
    h = eta-b,
    u = q/h,

    U_t + F(U)_x = S,

    F(U) = ( q+q_b,
             q*u + (eta^2-2*eta*b)/(2 Fr^2),
             q_b )^T,

    S = (0, -eta*b_x/Fr^2, 0)^T,

    q_b = xi*A*u^3,  xi=1/(1-rho0).

The local space--time predictor is the triangular Taylor polynomial

    U_tau(x,t) = sum_{kt=0}^k sum_{kx=0}^{k-kt}
                 U_tilde(kx,kt) (x-x_j)^kx (t-t^n)^kt,

and its coefficients are generated by the differential-transformation (DT)
recurrence from the notes:

    U_tilde(kx,kt+1)
      = -(kx+1)/(kt+1) F_tilde(kx+1,kt)
        + 1/(kt+1) S_tilde(kx,kt).                         (11)

F_tilde and S_tilde are assembled exactly from the DT product/inverse rules
and the G1,...,G4 / Q1,Q2 decomposition in equation (12) of the notes.

The one-stage DG correction is then performed with time-dependent predictor
traces at cell interfaces. A hydrostatic reconstruction is used for the water
part of the numerical flux. The hydrostatic momentum flux is transformed to
THE PRE-BALANCED FLUX USED IN THE NOTES by subtracting b^2/(2 Fr^2) on the
corresponding side of each interface. This gives exact lake-at-rest balance
for piecewise constant topography and is consistent with the interior
pre-balanced flux/source pair.

For discontinuous benchmark data, a conservative troubled-cell minmod limiter
is applied after the one-stage correction, as anticipated by the stabilization
remark in the notes. Cell averages are unchanged. A positivity scaling limiter
is also applied to nonconstant modes if necessary.

Default benchmark
-----------------
Siviglia, Vanzo & Toro (2022), Riemann Test 1, with the same dimensional data
as the previously supplied finite-volume reference code. The data are first
nondimensionalized, so replacing gravity by 1/Fr^2 is dimensionally correct.

Default ADER--DG settings
-------------------------
Polynomial degree k = 2.
CFL = 0.18 (the value used for 1D k=2 experiments in the DT-ADER-DG SWE paper).
200 cells and T=2 s (benchmark values).

Outputs
-------
ader_dg_sw_exner_solution.csv
ader_dg_sw_exner_solution.pt
ader_dg_vs_reference.png
ader_dg_validation.txt
ADER_DG_SW_Exner_eta_q_topography.gif

The animation is generated from snapshots recorded during the SAME adaptive
ADER--DG run; the PDE is not rerun only for the GIF.

Requires: torch, numpy, matplotlib, pillow.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import csv
import math
import time
import io
from typing import Tuple

import numpy as np
import torch
import matplotlib.pyplot as plt
from PIL import Image


# =============================================================================
# GLOBAL PARAMETERS
# =============================================================================

DTYPE = torch.float64
DEVICE = torch.device("cpu")
torch.set_default_dtype(DTYPE)

# Physical constants used only for nondimensionalization.
G_PHYS = 9.81  # m/s^2

# ---- Siviglia--Vanzo--Toro (2022), Riemann Test 1 ----
XMIN_PHYS = -15.0       # m
XMAX_PHYS = 15.0        # m
N_ELEMS = 200
TFINAL_PHYS = 2.0       # s

H_LEFT_PHYS = 2.0       # m
Q_LEFT_PHYS = 0.5       # m^2/s
B_LEFT_PHYS = 3.0       # m
H_RIGHT_PHYS = 2.0      # m
Q_RIGHT_PHYS = 4.34297  # m^2/s
B_RIGHT_PHYS = 2.84751  # m

M_GRASS = 3
AG_EFFECTIVE_PHYS = 0.01   # q_b = Ag*u^3 in the benchmark convention
RHO0 = 0.40
XI = 1.0 / (1.0 - RHO0)
A_GRASS_PHYS = (1.0 - RHO0) * AG_EFFECTIVE_PHYS

# Reference scales: same as in the earlier FV reference solver.
H_REF = H_LEFT_PHYS
U_REF = Q_LEFT_PHYS / H_LEFT_PHYS
L_REF = XMAX_PHYS - XMIN_PHYS
T_REF = L_REF / U_REF
Q_REF = H_REF * U_REF

FR = U_REF / math.sqrt(G_PHYS * H_REF)
INV_FR2 = 1.0 / (FR * FR)

# Nondimensional Grass coefficient; XI*A_GRASS = AG_EFFECTIVE.
AG_EFFECTIVE = AG_EFFECTIVE_PHYS * U_REF ** (M_GRASS - 1) / H_REF
A_GRASS = (1.0 - RHO0) * AG_EFFECTIVE

# ADER--DG controls.
POLY_DEGREE = 2
CFL_DG = 0.18
H_FLOOR = 1.0e-10
MAX_STEPS = 200000

# Quadrature. k+2 is sufficient for the polynomial volume integrands used
# here; one extra point is inexpensive and gives a robust time integration of
# the nonlinear interface Rusanov/hydrostatic flux.
NQ_SPACE = POLY_DEGREE + 2
NQ_TIME = POLY_DEGREE + 2

# Limiter parameters for the discontinuous Riemann benchmark.
USE_TROUBLED_CELL_LIMITER = True
MINMOD_BETA = 1.5
TVB_M = 20.0

OUTPUT_DIR = Path(__file__).resolve().parent
CSV_PATH = OUTPUT_DIR / "ader_dg_sw_exner_solution_Nref5000.csv"
PT_PATH = OUTPUT_DIR / "ader_dg_sw_exner_solution_Nref5000.pt"
PLOT_PATH = OUTPUT_DIR / "ader_dg_vs_reference_N5000.png"
VALIDATION_PATH = OUTPUT_DIR / "ader_dg_validation_Nref5000.txt"
REFERENCE_SCRIPT = OUTPUT_DIR / "sw_exner_reference_N5000_pytorch.py"

# Animation controls. Snapshots are recorded after EVERY adaptive ADER--DG
# time step, then a smaller set of evenly spaced physical times is selected
# for the GIF. This does not alter the numerical time stepping.
MAKE_ANIMATION = True
N_ANIMATION_FRAMES = 91
GIF_FRAME_DURATION_MS = 90
GIF_FINAL_HOLD_FRAMES = 6
GIF_PATH = OUTPUT_DIR / "ADER_DG_SW_Exner_eta_q_topography.gif"


# =============================================================================
# BASIC POLYNOMIAL / QUADRATURE UTILITIES
# =============================================================================


def gauss_legendre(n: int, a: float = -1.0, b: float = 1.0) -> Tuple[torch.Tensor, torch.Tensor]:
    x, w = np.polynomial.legendre.leggauss(n)
    x = 0.5 * (b - a) * x + 0.5 * (a + b)
    w = 0.5 * (b - a) * w
    return (
        torch.tensor(x, dtype=DTYPE, device=DEVICE),
        torch.tensor(w, dtype=DTYPE, device=DEVICE),
    )


def legendre_values(k: int, xi: torch.Tensor) -> torch.Tensor:
    """Return P_l(xi), shape (k+1, nq)."""
    vals = []
    x_np = xi.detach().cpu().numpy()
    for ell in range(k + 1):
        c = np.zeros(ell + 1)
        c[-1] = 1.0
        vals.append(torch.tensor(np.polynomial.legendre.legval(x_np, c), dtype=DTYPE, device=DEVICE))
    return torch.stack(vals, dim=0)


def legendre_derivative_values(k: int, xi: torch.Tensor) -> torch.Tensor:
    """Return dP_l/dxi(xi), shape (k+1, nq)."""
    vals = []
    x_np = xi.detach().cpu().numpy()
    for ell in range(k + 1):
        c = np.zeros(ell + 1)
        c[-1] = 1.0
        dc = np.polynomial.legendre.legder(c)
        vals.append(torch.tensor(np.polynomial.legendre.legval(x_np, dc), dtype=DTYPE, device=DEVICE))
    return torch.stack(vals, dim=0)


def legendre_at_endpoints(k: int) -> Tuple[torch.Tensor, torch.Tensor]:
    p_plus = torch.ones(k + 1, dtype=DTYPE, device=DEVICE)
    p_minus = torch.tensor([(-1.0) ** ell for ell in range(k + 1)], dtype=DTYPE, device=DEVICE)
    return p_minus, p_plus


def modal_to_spatial_taylor(modal: torch.Tensor, dx: float) -> torch.Tensor:
    """
    Convert U_h = sum_l a_l P_l(xi), xi=2(x-xj)/dx, to the exact local
    spatial Taylor coefficients U_tilde(kx,0) from equation (10b).

    modal shape: (N, 3, k+1)
    returns:     (N, 3, k+1)
    """
    N, nvar, kp1 = modal.shape
    k = kp1 - 1
    out = torch.zeros_like(modal)
    for ell in range(k + 1):
        leg = np.zeros(ell + 1)
        leg[-1] = 1.0
        # Power coefficients of P_ell(xi): sum_r p_r xi^r.
        p = np.polynomial.legendre.leg2poly(leg)
        for r, coeff in enumerate(p):
            out[:, :, r] += modal[:, :, ell] * (float(coeff) * (2.0 / dx) ** r)
    return out


def evaluate_modal(modal: torch.Tensor, xi: torch.Tensor) -> torch.Tensor:
    """Evaluate modal polynomial. Output shape (N,3,nq)."""
    P = legendre_values(modal.shape[-1] - 1, xi)
    return torch.einsum("nvl,lq->nvq", modal, P)


# =============================================================================
# MODEL AND INITIAL DATA
# =============================================================================


def grass_flux(u: torch.Tensor) -> torch.Tensor:
    return XI * A_GRASS * u * torch.abs(u).pow(M_GRASS - 1)


def initial_state_nd(x: torch.Tensor) -> torch.Tensor:
    """Return U=(eta,q,b) for the published Riemann data, nondimensional."""
    left = x < 0.0

    hL = H_LEFT_PHYS / H_REF
    qL = Q_LEFT_PHYS / Q_REF
    bL = B_LEFT_PHYS / H_REF
    hR = H_RIGHT_PHYS / H_REF
    qR = Q_RIGHT_PHYS / Q_REF
    bR = B_RIGHT_PHYS / H_REF

    h = torch.where(left, torch.full_like(x, hL), torch.full_like(x, hR))
    q = torch.where(left, torch.full_like(x, qL), torch.full_like(x, qR))
    b = torch.where(left, torch.full_like(x, bL), torch.full_like(x, bR))
    eta = h + b
    return torch.stack((eta, q, b), dim=1)


def project_initial_condition(x_centers: torch.Tensor, dx: float, k: int) -> torch.Tensor:
    """Componentwise L2 projection onto Legendre P^k in every cell."""
    xi, w = gauss_legendre(max(k + 2, 4))
    P = legendre_values(k, xi)
    xq = x_centers[:, None] + 0.5 * dx * xi[None, :]
    Uq = initial_state_nd(xq.reshape(-1)).reshape(x_centers.numel(), xi.numel(), 3).permute(0, 2, 1)

    modal = torch.zeros((x_centers.numel(), 3, k + 1), dtype=DTYPE, device=DEVICE)
    for ell in range(k + 1):
        # a_l = (2l+1)/2 * integral_{-1}^1 U P_l dxi
        modal[:, :, ell] = 0.5 * (2 * ell + 1) * torch.sum(
            Uq * (w * P[ell])[None, None, :], dim=-1
        )
    return modal


# =============================================================================
# DIFFERENTIAL TRANSFORMATION: equations (11)--(12)
# =============================================================================


def series_mul(A: torch.Tensor, B: torch.Tensor, k: int, max_t: int) -> torch.Tensor:
    """
    Truncated 2D Taylor-series product in (x,t).
    A,B shape (N,k+1,k+1), indexed [cell,kx,kt].
    """
    C = torch.zeros_like(A)
    for total in range(k + 1):
        for kt in range(min(total, max_t) + 1):
            kx = total - kt
            if kx > k:
                continue
            val = torch.zeros(A.shape[0], dtype=DTYPE, device=DEVICE)
            for r in range(kx + 1):
                for s in range(kt + 1):
                    val = val + A[:, r, s] * B[:, kx - r, kt - s]
            C[:, kx, kt] = val
    return C


def series_inverse(H: torch.Tensor, k: int, max_t: int) -> torch.Tensor:
    """DT recursion for R=1/H, exactly as written in the notes."""
    R = torch.zeros_like(H)
    h00 = H[:, 0, 0]
    if torch.any(h00 <= H_FLOOR):
        raise FloatingPointError(f"Non-positive predictor-center depth: min={h00.min().item():.3e}")
    R[:, 0, 0] = 1.0 / h00

    for total in range(1, k + 1):
        for kt in range(min(total, max_t) + 1):
            kx = total - kt
            if kx > k:
                continue
            acc = torch.zeros(H.shape[0], dtype=DTYPE, device=DEVICE)
            for r in range(kx + 1):
                for s in range(kt + 1):
                    if r == 0 and s == 0:
                        continue
                    acc = acc + H[:, r, s] * R[:, kx - r, kt - s]
            R[:, kx, kt] = -acc / h00
    return R


def transformed_flux_source(Uc: torch.Tensor, k: int, max_t: int) -> Tuple[torch.Tensor, torch.Tensor, dict]:
    """
    Construct F_tilde and S_tilde from equation (12) and all intermediate
    transformed quantities Q1,Q2,G1,...,G4.

    Uc shape: (N,3,k+1,k+1) with variable order eta,q,b.
    """
    eta = Uc[:, 0]
    q = Uc[:, 1]
    b = Uc[:, 2]
    h = eta - b

    R = series_inverse(h, k, max_t)
    u = series_mul(q, R, k, max_t)
    u2 = series_mul(u, u, k, max_t)
    u3 = series_mul(u2, u, k, max_t)

    Q2 = (XI * A_GRASS) * u3
    Q1 = q + Q2

    G1 = series_mul(q, u, k, max_t)
    eta2 = series_mul(eta, eta, k, max_t)
    etab = series_mul(eta, b, k, max_t)
    G2 = 0.5 * INV_FR2 * eta2
    G3 = INV_FR2 * etab

    bx = torch.zeros_like(b)
    for kt in range(max_t + 1):
        for kx in range(k):
            if kx + kt <= k - 1:
                bx[:, kx, kt] = (kx + 1) * b[:, kx + 1, kt]
    etabx = series_mul(eta, bx, k, max_t)
    G4 = INV_FR2 * etabx

    F = torch.zeros_like(Uc)
    S = torch.zeros_like(Uc)
    F[:, 0] = Q1
    F[:, 1] = G1 + G2 - G3
    F[:, 2] = Q2
    S[:, 1] = -G4

    aux = {
        "h": h,
        "R": R,
        "u": u,
        "u2": u2,
        "Q1": Q1,
        "Q2": Q2,
        "G1": G1,
        "G2": G2,
        "G3": G3,
        "G4": G4,
        "bx": bx,
    }
    return F, S, aux


def local_space_time_predictor(modal: torch.Tensor, dx: float) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """Build U_tilde, F_tilde, S_tilde in every cell via (11)--(12)."""
    N, _, kp1 = modal.shape
    k = kp1 - 1
    Uc = torch.zeros((N, 3, k + 1, k + 1), dtype=DTYPE, device=DEVICE)
    Uc[:, :, :, 0] = modal_to_spatial_taylor(modal, dx)

    # Successively increase temporal order, exactly following (11).
    for kt in range(k):
        F, S, _ = transformed_flux_source(Uc, k, max_t=kt)
        for kx in range(k - kt):
            Uc[:, :, kx, kt + 1] = (
                -float(kx + 1) / float(kt + 1) * F[:, :, kx + 1, kt]
                + 1.0 / float(kt + 1) * S[:, :, kx, kt]
            )

    F, S, _ = transformed_flux_source(Uc, k, max_t=k)
    return Uc, F, S


def eval_series(C: torch.Tensor, z: torch.Tensor, tloc: torch.Tensor, k: int) -> torch.Tensor:
    """
    Evaluate C(kx,kt) z^kx t^kt.
    C shape (N,3,k+1,k+1).
    z and tloc are broadcastable tensors. The common use below is scalar z/t
    or vectors handled one point at a time.
    """
    out = torch.zeros((C.shape[0], 3), dtype=DTYPE, device=DEVICE)
    for kt in range(k + 1):
        for kx in range(k - kt + 1):
            out = out + C[:, :, kx, kt] * (z ** kx) * (tloc ** kt)
    return out


# =============================================================================
# WELL-BALANCED INTERFACE FLUX IN THE PRE-BALANCED VARIABLES
# =============================================================================


def rusanov_hydro_flux(hL: torch.Tensor, qL: torch.Tensor, hR: torch.Tensor, qR: torch.Tensor):
    hLs = hL.clamp_min(H_FLOOR)
    hRs = hR.clamp_min(H_FLOOR)
    uL = qL / hLs
    uR = qR / hRs

    FL = torch.stack((qL, qL * uL + 0.5 * INV_FR2 * hL * hL), dim=-1)
    FRv = torch.stack((qR, qR * uR + 0.5 * INV_FR2 * hR * hR), dim=-1)
    a = torch.maximum(torch.abs(uL) + torch.sqrt(hLs) / FR,
                      torch.abs(uR) + torch.sqrt(hRs) / FR)
    jump = torch.stack((hR - hL, qR - qL), dim=-1)
    return 0.5 * (FL + FRv) - 0.5 * a[:, None] * jump


def interface_prebalanced_flux(UL: torch.Tensor, UR: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
    """
    Hydrostatic reconstruction at all interfaces.

    UL,UR shape (Ninterfaces,3), variables (eta,q,b).

    Returns two fluxes because hydrostatic source corrections are cell-side
    dependent:
      F_for_left_cell  -- used at the right boundary of the cell on the left,
      F_for_right_cell -- used at the left boundary of the cell on the right.

    The momentum component is transformed from the standard h-form to the
    pre-balanced flux of the notes via -b_side^2/(2 Fr^2).
    """
    etaL, qL, bL = UL[:, 0], UL[:, 1], UL[:, 2]
    etaR, qR, bR = UR[:, 0], UR[:, 1], UR[:, 2]
    hL = etaL - bL
    hR = etaR - bR

    if torch.any(hL <= 0.0) or torch.any(hR <= 0.0):
        raise FloatingPointError(
            f"Non-positive interface depth: minL={hL.min().item():.3e}, minR={hR.min().item():.3e}"
        )

    bstar = torch.maximum(bL, bR)
    hLstar = torch.clamp(etaL - bstar, min=0.0)
    hRstar = torch.clamp(etaR - bstar, min=0.0)

    ratioL = torch.where(hL > H_FLOOR, hLstar / hL, torch.zeros_like(hL))
    ratioR = torch.where(hR > H_FLOOR, hRstar / hR, torch.zeros_like(hR))
    qLstar = qL * ratioL
    qRstar = qR * ratioR

    Fstar = rusanov_hydro_flux(hLstar, qLstar, hRstar, qRstar)

    corrL = 0.5 * INV_FR2 * (hL * hL - hLstar * hLstar)
    corrR = 0.5 * INV_FR2 * (hR * hR - hRstar * hRstar)
    Fstd_mom_L = Fstar[:, 1] + corrL
    Fstd_mom_R = Fstar[:, 1] + corrR

    # Transform standard momentum flux to the pre-balanced momentum flux.
    Fpre_mom_L = Fstd_mom_L - 0.5 * INV_FR2 * bL * bL
    Fpre_mom_R = Fstd_mom_R - 0.5 * INV_FR2 * bR * bR

    uL = qL / hL.clamp_min(H_FLOOR)
    uR = qR / hR.clamp_min(H_FLOOR)
    qbL = grass_flux(uL)
    qbR = grass_flux(uR)
    qb = torch.where(Fstar[:, 0] >= 0.0, qbL, qbR)

    F_left = torch.stack((Fstar[:, 0] + qb, Fpre_mom_L, qb), dim=-1)
    F_right = torch.stack((Fstar[:, 0] + qb, Fpre_mom_R, qb), dim=-1)
    return F_left, F_right


def predictor_interface_states(Uc: torch.Tensor, dx: float, tloc: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
    """Return each cell's left/right predictor trace at local time tloc."""
    k = Uc.shape[-1] - 1
    zL = torch.tensor(-0.5 * dx, dtype=DTYPE, device=DEVICE)
    zR = torch.tensor(+0.5 * dx, dtype=DTYPE, device=DEVICE)
    cell_left = eval_series(Uc, zL, tloc, k)
    cell_right = eval_series(Uc, zR, tloc, k)
    return cell_left, cell_right


def all_interface_states(cell_left: torch.Tensor, cell_right: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
    """Transmissive boundaries; returns UL/UR for N+1 interfaces."""
    N = cell_left.shape[0]
    UL = torch.empty((N + 1, 3), dtype=DTYPE, device=DEVICE)
    UR = torch.empty((N + 1, 3), dtype=DTYPE, device=DEVICE)

    # Interior interfaces i=1,...,N-1: left cell i-1, right cell i.
    UL[1:N] = cell_right[:-1]
    UR[1:N] = cell_left[1:]

    # Transmissive boundaries.
    UL[0] = cell_left[0]
    UR[0] = cell_left[0]
    UL[N] = cell_right[-1]
    UR[N] = cell_right[-1]
    return UL, UR


# =============================================================================
# DG CORRECTION, LIMITING, CFL
# =============================================================================


def dg_one_stage_update(modal: torch.Tensor, Uc: torch.Tensor, Fc: torch.Tensor, Sc: torch.Tensor,
                        dx: float, dt: float) -> torch.Tensor:
    """Equation (7): volume + source + time-integrated interface fluxes."""
    N, _, kp1 = modal.shape
    k = kp1 - 1

    xi, wx = gauss_legendre(NQ_SPACE)
    theta, wt = gauss_legendre(NQ_TIME, 0.0, 1.0)
    P = legendre_values(k, xi)
    dP = legendre_derivative_values(k, xi)
    Pminus, Pplus = legendre_at_endpoints(k)

    # Volume/source integrals.
    vol = torch.zeros((N, 3, k + 1), dtype=DTYPE, device=DEVICE)
    src = torch.zeros_like(vol)
    for it in range(theta.numel()):
        tloc = dt * theta[it]
        for ix in range(xi.numel()):
            z = 0.5 * dx * xi[ix]
            Fq = eval_series(Fc, z, tloc, k)
            Sq = eval_series(Sc, z, tloc, k)
            weight = dt * wt[it] * wx[ix]
            for ell in range(k + 1):
                # dx/2 * d/dx(P_l) = d/dxi(P_l)
                vol[:, :, ell] += weight * Fq * dP[ell, ix]
                src[:, :, ell] += weight * (0.5 * dx) * Sq * P[ell, ix]

    # Time-integrated interface fluxes.
    Fhat_for_left_cell = torch.zeros((N + 1, 3), dtype=DTYPE, device=DEVICE)
    Fhat_for_right_cell = torch.zeros_like(Fhat_for_left_cell)
    for it in range(theta.numel()):
        tloc = dt * theta[it]
        cell_left, cell_right = predictor_interface_states(Uc, dx, tloc)
        UL, UR = all_interface_states(cell_left, cell_right)
        FL, FR = interface_prebalanced_flux(UL, UR)
        Fhat_for_left_cell += dt * wt[it] * FL
        Fhat_for_right_cell += dt * wt[it] * FR

    new = torch.empty_like(modal)
    for ell in range(k + 1):
        M = dx / float(2 * ell + 1)
        rhs = M * modal[:, :, ell] + vol[:, :, ell] + src[:, :, ell]
        # right interface index j+1 uses left-cell corrected flux;
        # left interface index j uses right-cell corrected flux.
        rhs -= Fhat_for_left_cell[1:] * Pplus[ell]
        rhs += Fhat_for_right_cell[:-1] * Pminus[ell]
        new[:, :, ell] = rhs / M
    return new


def minmod3(a: torch.Tensor, b: torch.Tensor, c: torch.Tensor) -> torch.Tensor:
    same = ((a > 0) & (b > 0) & (c > 0)) | ((a < 0) & (b < 0) & (c < 0))
    mag = torch.minimum(torch.abs(a), torch.minimum(torch.abs(b), torch.abs(c)))
    return torch.where(same, torch.sign(a) * mag, torch.zeros_like(a))


def troubled_cell_limiter(modal: torch.Tensor, dx: float) -> Tuple[torch.Tensor, int]:
    """
    Conservative P2->P1 limiter in troubled cells. The detector checks h,q,b
    against neighboring cell-average ranges. All three conserved variables are
    limited together in a troubled cell; the cell average is untouched.
    """
    if modal.shape[-1] <= 1 or not USE_TROUBLED_CELL_LIMITER:
        return modal, 0

    k = modal.shape[-1] - 1
    xi_check = torch.tensor([-1.0, -0.5, 0.0, 0.5, 1.0], dtype=DTYPE, device=DEVICE)
    vals = evaluate_modal(modal, xi_check)  # N,3,nq
    hvals = vals[:, 0] - vals[:, 2]
    indicators = torch.stack((hvals, vals[:, 1], vals[:, 2]), dim=1)  # N,3,nq

    avgU = modal[:, :, 0]
    avg_ind = torch.stack((avgU[:, 0] - avgU[:, 2], avgU[:, 1], avgU[:, 2]), dim=1)
    avg_pad = torch.cat((avg_ind[:1], avg_ind, avg_ind[-1:]), dim=0)
    lo = torch.minimum(avg_pad[:-2], torch.minimum(avg_pad[1:-1], avg_pad[2:]))
    hi = torch.maximum(avg_pad[:-2], torch.maximum(avg_pad[1:-1], avg_pad[2:]))

    tol = TVB_M * dx * dx
    troubled = torch.any((indicators < (lo[:, :, None] - tol)) | (indicators > (hi[:, :, None] + tol)), dim=(1, 2))

    out = modal.clone()
    if not torch.any(troubled):
        return out, 0

    # Neighbor means of U=(eta,q,b), transmissive at boundaries.
    avg_padU = torch.cat((avgU[:1], avgU, avgU[-1:]), dim=0)
    dm = avgU - avg_padU[:-2]
    dp = avg_padU[2:] - avgU
    a1 = out[:, :, 1]
    limited_a1 = minmod3(a1, MINMOD_BETA * dm, MINMOD_BETA * dp)

    out[troubled, :, 1] = limited_a1[troubled]
    if k >= 2:
        out[troubled, :, 2:] = 0.0
    return out, int(troubled.sum().item())


def positivity_scale(modal: torch.Tensor) -> Tuple[torch.Tensor, int]:
    """Scale nonconstant modes toward the cell average if h=eta-b gets small."""
    if modal.shape[-1] <= 1:
        hbar = modal[:, 0, 0] - modal[:, 2, 0]
        if torch.any(hbar <= H_FLOOR):
            raise FloatingPointError(f"Non-positive cell-average depth: {hbar.min().item():.3e}")
        return modal, 0

    hbar = modal[:, 0, 0] - modal[:, 2, 0]
    if torch.any(hbar <= H_FLOOR):
        raise FloatingPointError(f"Non-positive cell-average depth: {hbar.min().item():.3e}")

    xi = torch.linspace(-1.0, 1.0, 17, dtype=DTYPE, device=DEVICE)
    vals = evaluate_modal(modal, xi)
    h = vals[:, 0] - vals[:, 2]
    hmin = h.min(dim=1).values
    needs = hmin < H_FLOOR
    if not torch.any(needs):
        return modal, 0

    theta = torch.ones_like(hbar)
    theta[needs] = torch.clamp(
        (hbar[needs] - H_FLOOR) / (hbar[needs] - hmin[needs] + 1.0e-30),
        min=0.0,
        max=1.0,
    )
    out = modal.clone()
    out[:, :, 1:] *= theta[:, None, None]
    return out, int(needs.sum().item())


def compute_dt(modal: torch.Tensor, dx: float, t: float, tfinal: float) -> float:
    avg = modal[:, :, 0]
    h = (avg[:, 0] - avg[:, 2]).clamp_min(H_FLOOR)
    u = avg[:, 1] / h
    speed = torch.abs(u) + torch.sqrt(h) / FR
    amax = float(speed.max().item())
    dt = CFL_DG * dx / max(amax, 1.0e-14)
    return min(dt, tfinal - t)


# =============================================================================
# SOLVER / VALIDATION
# =============================================================================


@dataclass
class DGSolution:
    x_nd: torch.Tensor
    modal_initial: torch.Tensor
    modal_final: torch.Tensor
    time_nd: float
    nsteps: int
    dt_min_phys: float
    dt_max_phys: float
    dt_mean_phys: float
    total_troubled: int
    total_positivity_scaled: int
    wall_seconds: float

    # Cell-average snapshots from the SAME adaptive ADER--DG trajectory.
    # Shapes:
    #   snapshot_times_phys : (nsnap,)
    #   snapshot_eta_phys   : (nsnap, N_ELEMS)
    #   snapshot_q_phys     : (nsnap, N_ELEMS)
    #   snapshot_b_phys     : (nsnap, N_ELEMS)
    snapshot_times_phys: np.ndarray
    snapshot_eta_phys: np.ndarray
    snapshot_q_phys: np.ndarray
    snapshot_b_phys: np.ndarray

    @property
    def avg(self):
        return self.modal_final[:, :, 0]

    @property
    def eta_phys(self):
        return self.avg[:, 0] * H_REF

    @property
    def q_phys(self):
        return self.avg[:, 1] * Q_REF

    @property
    def b_phys(self):
        return self.avg[:, 2] * H_REF

    @property
    def h_phys(self):
        return (self.avg[:, 0] - self.avg[:, 2]) * H_REF

    @property
    def x_phys(self):
        return self.x_nd * L_REF


def run_ader_dg(verbose: bool = True) -> DGSolution:
    xmin = XMIN_PHYS / L_REF
    xmax = XMAX_PHYS / L_REF
    dx = (xmax - xmin) / N_ELEMS
    x = torch.linspace(xmin + 0.5 * dx, xmax - 0.5 * dx, N_ELEMS, dtype=DTYPE, device=DEVICE)
    modal = project_initial_condition(x, dx, POLY_DEGREE)
    modal0 = modal.clone()

    tfinal = TFINAL_PHYS / T_REF
    t = 0.0
    nsteps = 0
    dts = []
    total_troubled = 0
    total_pos = 0

    # Record the initial cell averages. These histories are used only for
    # visualization and do not feed back into the solver.
    snapshot_times_phys = [0.0]
    snapshot_eta_phys = [(modal[:, 0, 0] * H_REF).detach().cpu().numpy().copy()]
    snapshot_q_phys = [(modal[:, 1, 0] * Q_REF).detach().cpu().numpy().copy()]
    snapshot_b_phys = [(modal[:, 2, 0] * H_REF).detach().cpu().numpy().copy()]

    t0 = time.perf_counter()

    while t < tfinal - 1.0e-15:
        if nsteps >= MAX_STEPS:
            raise RuntimeError("Exceeded MAX_STEPS")
        dt = compute_dt(modal, dx, t, tfinal)

        # Predictor (11)--(12).
        Uc, Fc, Sc = local_space_time_predictor(modal, dx)

        # One-stage correction (7).
        trial = dg_one_stage_update(modal, Uc, Fc, Sc, dx, dt)
        if not torch.isfinite(trial).all():
            raise FloatingPointError(f"Non-finite DG state at step {nsteps}, t={t*T_REF:.6e}s")

        trial, ntr = troubled_cell_limiter(trial, dx)
        trial, npos = positivity_scale(trial)

        modal = trial
        t += dt
        nsteps += 1
        dts.append(dt * T_REF)
        total_troubled += ntr
        total_pos += npos

        # Save the accepted state after this adaptive ADER--DG step.
        snapshot_times_phys.append(t * T_REF)
        snapshot_eta_phys.append((modal[:, 0, 0] * H_REF).detach().cpu().numpy().copy())
        snapshot_q_phys.append((modal[:, 1, 0] * Q_REF).detach().cpu().numpy().copy())
        snapshot_b_phys.append((modal[:, 2, 0] * H_REF).detach().cpu().numpy().copy())

        if verbose and (nsteps % 100 == 0 or t >= tfinal - 1e-15):
            avg = modal[:, :, 0]
            hmin = float((avg[:, 0] - avg[:, 2]).min().item()) * H_REF
            print(f"step={nsteps:5d}  t={t*T_REF:10.6f}s  dt={dt*T_REF:.3e}s  min(hbar)={hmin:.6e}m  troubled={ntr}")

    wall = time.perf_counter() - t0
    return DGSolution(
        x_nd=x,
        modal_initial=modal0,
        modal_final=modal,
        time_nd=t,
        nsteps=nsteps,
        dt_min_phys=min(dts),
        dt_max_phys=max(dts),
        dt_mean_phys=sum(dts) / len(dts),
        total_troubled=total_troubled,
        total_positivity_scaled=total_pos,
        wall_seconds=wall,
        snapshot_times_phys=np.asarray(snapshot_times_phys),
        snapshot_eta_phys=np.asarray(snapshot_eta_phys),
        snapshot_q_phys=np.asarray(snapshot_q_phys),
        snapshot_b_phys=np.asarray(snapshot_b_phys),
    )


def lake_at_rest_residual_test() -> Tuple[float, float, float]:
    """
    One-step DG check for q=0, eta=constant, discontinuous b. Report max
    change in cell averages divided by dt. Uses degree 0 deliberately so the
    discontinuous-bed balance is tested without polynomial projection artifacts.
    """
    xmin = XMIN_PHYS / L_REF
    xmax = XMAX_PHYS / L_REF
    dx = (xmax - xmin) / N_ELEMS
    x = torch.linspace(xmin + 0.5 * dx, xmax - 0.5 * dx, N_ELEMS, dtype=DTYPE, device=DEVICE)

    k = 0
    modal = torch.zeros((N_ELEMS, 3, 1), dtype=DTYPE, device=DEVICE)
    bL = B_LEFT_PHYS / H_REF
    bR = B_RIGHT_PHYS / H_REF
    b = torch.where(x < 0.0, torch.full_like(x, bL), torch.full_like(x, bR))
    eta = torch.full_like(x, 2.5)
    modal[:, 0, 0] = eta
    modal[:, 1, 0] = 0.0
    modal[:, 2, 0] = b

    # Build degree-0 predictor directly.
    Uc = torch.zeros((N_ELEMS, 3, 1, 1), dtype=DTYPE, device=DEVICE)
    Uc[:, :, 0, 0] = modal[:, :, 0]
    Fc, Sc, _ = transformed_flux_source(Uc, k=0, max_t=0)
    dt = 1.0e-6

    # Local degree-0 update specialized from dg_one_stage_update to avoid using
    # global POLY_DEGREE quadrature assumptions.
    cell_left = Uc[:, :, 0, 0]
    cell_right = cell_left
    UL, UR = all_interface_states(cell_left, cell_right)
    FL, FR = interface_prebalanced_flux(UL, UR)

    newavg = modal[:, :, 0].clone()
    newavg -= (dt / dx) * (FL[1:] - FR[:-1])
    # Source is zero in each piecewise-constant cell; interface correction
    # accounts for the bed jump.
    residual = (newavg - modal[:, :, 0]) / dt
    return tuple(float(residual[:, i].abs().max().item()) for i in range(3))


def dt_identity_test(modal: torch.Tensor, dx: float) -> float:
    """
    Internal algebra check: after building the predictor, verify recurrence
    (11) at every coefficient. Returns max absolute coefficient residual.
    """
    Uc, Fc, Sc = local_space_time_predictor(modal, dx)
    k = modal.shape[-1] - 1
    rmax = 0.0
    for kt in range(k):
        for kx in range(k - kt):
            lhs = Uc[:, :, kx, kt + 1]
            rhs = -(kx + 1) / (kt + 1) * Fc[:, :, kx + 1, kt] + Sc[:, :, kx, kt] / (kt + 1)
            rmax = max(rmax, float((lhs - rhs).abs().max().item()))
    return rmax


def try_run_reference():
    """Run the previously supplied FV reference solver if it is adjacent."""
    if not REFERENCE_SCRIPT.exists():
        return None
    import importlib.util
    import sys
    spec = importlib.util.spec_from_file_location("fv_reference", REFERENCE_SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod.run_solver()



def p0_regression_against_reference(ref) -> dict:
    """
    Regression test of the pre-balanced interface treatment. With k=0 and the
    same CFL=0.9 as the finite-volume reference, the ADER-DG correction must
    reduce algebraically to that FV scheme for this piecewise-constant test.
    """
    if ref is None:
        return {}
    # This exact P0 regression is meaningful only when both solvers use the
    # same grid.  The production reference is now deliberately refined to
    # N_ref=5000 while ADER-DG uses N=200, so skip this same-grid identity test.
    if ref.x_phys.numel() != N_ELEMS:
        return {}
    xmin = XMIN_PHYS / L_REF
    xmax = XMAX_PHYS / L_REF
    dx = (xmax - xmin) / N_ELEMS
    x = torch.linspace(xmin + 0.5 * dx, xmax - 0.5 * dx, N_ELEMS, dtype=DTYPE, device=DEVICE)
    U = initial_state_nd(x)
    t = 0.0
    tfinal = TFINAL_PHYS / T_REF
    nsteps = 0
    while t < tfinal - 1.0e-15:
        h = (U[:, 0] - U[:, 2]).clamp_min(H_FLOOR)
        u = U[:, 1] / h
        amax = float((torch.abs(u) + torch.sqrt(h) / FR).max().item())
        dt = min(0.9 * dx / max(amax, 1.0e-14), tfinal - t)
        UL = torch.empty((N_ELEMS + 1, 3), dtype=DTYPE, device=DEVICE)
        UR = torch.empty_like(UL)
        UL[1:N_ELEMS] = U[:-1]
        UR[1:N_ELEMS] = U[1:]
        UL[0] = U[0]; UR[0] = U[0]
        UL[-1] = U[-1]; UR[-1] = U[-1]
        FLuxL, FLuxR = interface_prebalanced_flux(UL, UR)
        U = U - (dt / dx) * (FLuxL[1:] - FLuxR[:-1])
        t += dt
        nsteps += 1
    eta = U[:, 0] * H_REF
    q = U[:, 1] * Q_REF
    b = U[:, 2] * H_REF
    return {
        "P0_steps": nsteps,
        "P0_Linf_eta_vs_FV_m": float(torch.max(torch.abs(eta - ref.eta_phys)).item()),
        "P0_Linf_q_vs_FV_m2_s": float(torch.max(torch.abs(q - ref.q_phys)).item()),
        "P0_Linf_b_vs_FV_m": float(torch.max(torch.abs(b - ref.b_phys)).item()),
    }

def save_and_validate(sol: DGSolution, wb, dt_residual, ref, p0reg=None) -> dict:
    x = sol.x_phys
    avg0 = sol.modal_initial[:, :, 0]
    eta0 = avg0[:, 0] * H_REF
    q0 = avg0[:, 1] * Q_REF
    b0 = avg0[:, 2] * H_REF

    with CSV_PATH.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([
            "x_m", "eta_initial_m", "eta_ader_dg_m", "q_initial_m2_s",
            "q_ader_dg_m2_s", "b_initial_m", "b_ader_dg_m", "h_ader_dg_m"
        ])
        for row in zip(x.tolist(), eta0.tolist(), sol.eta_phys.tolist(), q0.tolist(),
                       sol.q_phys.tolist(), b0.tolist(), sol.b_phys.tolist(), sol.h_phys.tolist()):
            writer.writerow(row)

    metrics = {}
    ref_on_dg = None
    if ref is not None:
        # The refined FV reference uses N_ref=5000, while ADER-DG uses N=200.
        # Interpolate the fine-grid cell-center values to the DG cell centers
        # solely for pointwise error diagnostics. The plot keeps the full
        # 5000-cell reference curve.
        xdg = sol.x_phys.detach().cpu().numpy()
        xref = ref.x_phys.detach().cpu().numpy()
        eta_ref_i = torch.tensor(np.interp(xdg, xref, ref.eta_phys.detach().cpu().numpy()), dtype=DTYPE)
        q_ref_i = torch.tensor(np.interp(xdg, xref, ref.q_phys.detach().cpu().numpy()), dtype=DTYPE)
        b_ref_i = torch.tensor(np.interp(xdg, xref, ref.b_phys.detach().cpu().numpy()), dtype=DTYPE)
        ref_on_dg = (eta_ref_i, q_ref_i, b_ref_i)
        eta_dg = sol.eta_phys.detach().cpu()
        q_dg = sol.q_phys.detach().cpu()
        b_dg = sol.b_phys.detach().cpu()
        metrics["L1_eta_vs_FV5000_interp_m"] = float(torch.mean(torch.abs(eta_dg - eta_ref_i)).item())
        metrics["L1_q_vs_FV5000_interp_m2_s"] = float(torch.mean(torch.abs(q_dg - q_ref_i)).item())
        metrics["L1_b_vs_FV5000_interp_m"] = float(torch.mean(torch.abs(b_dg - b_ref_i)).item())
        metrics["Linf_eta_vs_FV5000_interp_m"] = float(torch.max(torch.abs(eta_dg - eta_ref_i)).item())
        metrics["Linf_q_vs_FV5000_interp_m2_s"] = float(torch.max(torch.abs(q_dg - q_ref_i)).item())
        metrics["Linf_b_vs_FV5000_interp_m"] = float(torch.max(torch.abs(b_dg - b_ref_i)).item())

    torch.save({
        "x_m": x,
        "eta_m": sol.eta_phys,
        "q_m2_s": sol.q_phys,
        "b_m": sol.b_phys,
        "h_m": sol.h_phys,
        "modal_nd": sol.modal_final,
        "degree": POLY_DEGREE,
        "Fr": FR,
        "1_over_Fr2": INV_FR2,
        "nsteps": sol.nsteps,
        "dt_min_s": sol.dt_min_phys,
        "dt_max_s": sol.dt_max_phys,
        "dt_mean_s": sol.dt_mean_phys,
        "lake_at_rest_residual": wb,
        "dt_recurrence_residual": dt_residual,
        "metrics_vs_fv": metrics,
    }, PT_PATH)

    # Plot the requested eta and q, plus b for morphodynamics, against FV.
    xp = x.cpu().numpy()
    fig, axes = plt.subplots(3, 1, figsize=(9.0, 10.0), sharex=True)
    axes[0].plot(xp, sol.eta_phys.cpu().numpy(), label="ADER-DG cell average")
    axes[1].plot(xp, sol.q_phys.cpu().numpy(), label="ADER-DG cell average")
    axes[2].plot(xp, sol.b_phys.cpu().numpy(), label="ADER-DG cell average")
    if ref is not None:
        xrefp = ref.x_phys.cpu().numpy()
        axes[0].plot(xrefp, ref.eta_phys.cpu().numpy(), "--", label="FV reference (N=5000)")
        axes[1].plot(xrefp, ref.q_phys.cpu().numpy(), "--", label="FV reference (N=5000)")
        axes[2].plot(xrefp, ref.b_phys.cpu().numpy(), "--", label="FV reference (N=5000)")
    axes[0].set_ylabel(r"$\eta$ [m]")
    axes[1].set_ylabel(r"$q$ [m$^2$/s]")
    axes[2].set_ylabel(r"$b$ [m]")
    axes[2].set_xlabel("x [m]")
    for ax in axes:
        ax.grid(True, alpha=0.25)
        ax.legend()
    fig.suptitle(f"1D low-Froude SW--Exner: ADER-DG P{POLY_DEGREE}, T={TFINAL_PHYS:g} s")
    fig.tight_layout()
    fig.savefig(PLOT_PATH, dpi=180)
    plt.close(fig)

    # Conservation diagnostics of eta and b: transmissive boundaries mean the
    # totals can change through boundary fluxes, so report only finite/ranges.
    lines = [
        "ADER--DG low-Froude shallow-water--Exner validation",
        "===================================================",
        f"Polynomial degree k             : {POLY_DEGREE}",
        f"ADER-DG cells                  : {N_ELEMS}",
        f"FV reference cells             : {ref.x_phys.numel() if ref is not None else 'N/A'}",
        f"FV reference dx [m]            : {(XMAX_PHYS-XMIN_PHYS)/ref.x_phys.numel():.8f}" if ref is not None else "FV reference dx [m]            : N/A",
        f"CFL (DG)                        : {CFL_DG}",
        f"Fr                              : {FR:.12e}",
        f"1/Fr^2                          : {INV_FR2:.12e}",
        f"Final time [s]                  : {sol.time_nd*T_REF:.12e}",
        f"Time steps                      : {sol.nsteps}",
        f"dt min/mean/max [s]             : {sol.dt_min_phys:.6e} / {sol.dt_mean_phys:.6e} / {sol.dt_max_phys:.6e}",
        f"Wall time [s]                   : {sol.wall_seconds:.3f}",
        f"Total troubled-cell limit events: {sol.total_troubled}",
        f"Total positivity-scale events   : {sol.total_positivity_scaled}",
        f"DT recurrence max residual      : {dt_residual:.6e}",
        f"Lake-at-rest residual eta       : {wb[0]:.6e}",
        f"Lake-at-rest residual q         : {wb[1]:.6e}",
        f"Lake-at-rest residual b         : {wb[2]:.6e}",
        f"Final h range [m]               : {sol.h_phys.min().item():.8f} .. {sol.h_phys.max().item():.8f}",
        f"Final eta range [m]             : {sol.eta_phys.min().item():.8f} .. {sol.eta_phys.max().item():.8f}",
        f"Final q range [m^2/s]           : {sol.q_phys.min().item():.8f} .. {sol.q_phys.max().item():.8f}",
        f"Final b range [m]               : {sol.b_phys.min().item():.8f} .. {sol.b_phys.max().item():.8f}",
    ]
    if p0reg:
        lines.append("\nP0 regression against the FV reference (same CFL=0.9):")
        for key, val in p0reg.items():
            if key == "P0_steps":
                lines.append(f"  {key:28s}: {val}")
            else:
                lines.append(f"  {key:28s}: {val:.8e}")
    if metrics:
        lines.append("\nComparison of ADER-DG P2 cell averages with the refined FV N=5000 reference\n(interpolated from FV cell centers to DG cell centers for diagnostics):")
        for key, val in metrics.items():
            lines.append(f"  {key:28s}: {val:.8e}")
    VALIDATION_PATH.write_text("\n".join(lines) + "\n")
    return metrics



def save_animation(sol: DGSolution, gif_path: Path = GIF_PATH) -> Path:
    """
    Create an animated GIF of eta(x,t), q(x,t), and the moving bed b(x,t).

    Important:
      * The frames come from snapshots recorded during the SAME adaptive
        ADER--DG run used for the final numerical solution.
      * No artificial animation time step is imposed.
      * The x/y axes are fixed over all frames so that apparent motion is
        physical/numerical evolution rather than axis rescaling.
    """
    times = sol.snapshot_times_phys
    eta_hist = sol.snapshot_eta_phys
    q_hist = sol.snapshot_q_phys
    b_hist = sol.snapshot_b_phys
    x_phys = sol.x_phys.detach().cpu().numpy()

    if len(times) < 2:
        raise RuntimeError("Not enough snapshots to build the animation")

    # Choose approximately evenly spaced PHYSICAL times, then use the nearest
    # state from the already recorded adaptive-time trajectory.
    target_times = np.linspace(0.0, TFINAL_PHYS, N_ANIMATION_FRAMES)
    frame_indices = np.unique(
        [int(np.argmin(np.abs(times - tt))) for tt in target_times]
    )
    frame_indices = np.unique(
        np.concatenate(([0], frame_indices, [len(times) - 1]))
    )

    def padded_limits(a: np.ndarray, frac: float = 0.07):
        amin = float(np.min(a))
        amax = float(np.max(a))
        span = amax - amin
        if span == 0.0:
            span = max(abs(amin), 1.0)
        return amin - frac * span, amax + frac * span

    eta_lim = padded_limits(eta_hist)
    q_lim = padded_limits(q_hist)
    b_lim = padded_limits(b_hist)

    frames = []

    for idx in frame_indices:
        fig = plt.figure(figsize=(9.2, 8.4))

        ax1 = fig.add_axes([0.11, 0.69, 0.84, 0.23])
        ax2 = fig.add_axes([0.11, 0.39, 0.84, 0.23])
        ax3 = fig.add_axes([0.11, 0.09, 0.84, 0.23])

        ax1.plot(x_phys, eta_hist[idx], linewidth=2)
        ax2.plot(x_phys, q_hist[idx], linewidth=2)
        ax3.plot(x_phys, b_hist[idx], linewidth=2)

        ax1.set_ylabel(r"$\eta$ [m]")
        ax2.set_ylabel(r"$q$ [m$^2$/s]")
        ax3.set_ylabel(r"$b$ [m]")
        ax3.set_xlabel(r"$x$ [m]")

        for ax in (ax1, ax2, ax3):
            ax.set_xlim(XMIN_PHYS, XMAX_PHYS)
            ax.grid(True, alpha=0.25)

        ax1.set_ylim(*eta_lim)
        ax2.set_ylim(*q_lim)
        ax3.set_ylim(*b_lim)

        fig.suptitle(
            f"1D low-Froude SW--Exner -- P{POLY_DEGREE} ADER--DG, "
            f"N = {N_ELEMS}, t = {times[idx]:.3f} s",
            fontsize=13,
            y=0.975,
        )
        fig.text(
            0.5,
            0.945,
            "Siviglia--Vanzo--Toro Riemann Test 1 | "
            "Grass sediment transport | moving bed",
            ha="center",
            va="center",
            fontsize=9,
        )

        buf = io.BytesIO()
        fig.savefig(buf, format="png", dpi=105)
        plt.close(fig)
        buf.seek(0)

        # Convert each PNG to an indexed palette suitable for a GIF.
        frames.append(
            Image.open(buf).convert("P", palette=Image.Palette.ADAPTIVE)
        )

    # Hold the final state slightly longer.
    frames_to_save = frames + [frames[-1]] * GIF_FINAL_HOLD_FRAMES
    frames_to_save[0].save(
        gif_path,
        save_all=True,
        append_images=frames_to_save[1:],
        duration=GIF_FRAME_DURATION_MS,
        loop=0,
        optimize=False,
    )

    return gif_path


def main():
    print("=== PyTorch ADER--DG low-Froude shallow-water--Exner solver ===")
    print(f"Fr={FR:.10f}, 1/Fr^2={INV_FR2:.6f}, k={POLY_DEGREE}, N={N_ELEMS}, CFL={CFL_DG}")

    wb = lake_at_rest_residual_test()
    print(f"lake-at-rest residual (eta,q,b): {wb}")

    # Algebraic recurrence test on the projected initial DG state.
    xmin = XMIN_PHYS / L_REF
    xmax = XMAX_PHYS / L_REF
    dx = (xmax - xmin) / N_ELEMS
    x = torch.linspace(xmin + 0.5 * dx, xmax - 0.5 * dx, N_ELEMS, dtype=DTYPE, device=DEVICE)
    modal0 = project_initial_condition(x, dx, POLY_DEGREE)
    dt_res = dt_identity_test(modal0, dx)
    print(f"DT recurrence max residual: {dt_res:.3e}")

    sol = run_ader_dg(verbose=True)
    print(f"ADER-DG complete: {sol.nsteps} steps, wall={sol.wall_seconds:.2f}s")

    ref = try_run_reference()
    p0reg = p0_regression_against_reference(ref)
    if p0reg:
        print("P0 regression against FV reference:")
        for key, val in p0reg.items():
            print(f"  {key}: {val}")
    metrics = save_and_validate(sol, wb, dt_res, ref, p0reg)
    if metrics:
        print("comparison with FV reference:")
        for key, val in metrics.items():
            print(f"  {key}: {val:.6e}")

    if MAKE_ANIMATION:
        gif_file = save_animation(sol)
        print(f"Animation  : {gif_file}")

    print(f"CSV        : {CSV_PATH}")
    print(f"PyTorch    : {PT_PATH}")
    print(f"Plot       : {PLOT_PATH}")
    print(f"Validation : {VALIDATION_PATH}")


if __name__ == "__main__":
    main()
